### ISSUE TITLE
Update for Shapely 2.0

### ISSUE THREAD

**Issue by sea-bass** [benjimin/descartes#5]
Today Shapely released a 2.0 version and my CI picked up a failure related to this.

If you `pip3 install shapely==2.0.0` and then run something like the following, you can reproduce the issue:

```
>>> from shapely import Polygon
>>> from descartes.patch import PolygonPatch

>>> poly = Polygon(((0., 0.), (0., 1.), (1., 1.), (1., 0.), (0., 0.)))
>>> patch = PolygonPatch(poly)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sebastian/python-virtualenvs/pyrobosim/lib/python3.10/site-packages/descartes/patch.py", line 87, in PolygonPatch
    return PathPatch(PolygonPath(polygon), **kwargs)
  File "/home/sebastian/python-virtualenvs/pyrobosim/lib/python3.10/site-packages/descartes/patch.py", line 62, in PolygonPath
    vertices = concatenate([
  File "/home/sebastian/python-virtualenvs/pyrobosim/lib/python3.10/site-packages/descartes/patch.py", line 63, in <listcomp>
    concatenate([asarray(t.exterior)[:, :2]] +
IndexError: too many indices for array: array is 0-dimensional, but 2 were indexed
```

**Comment by pdumon** [comment]
I think this was fixed in the code last year (uses `t.exterior.coords` now), but a release was never built.

**Comment by pdumon** [comment]
Also, I'm afraid this repo is a fork and not from the original author

**Comment by sea-bass** [comment]
Yeah, I think I'm better off using / modifying the built-in Shapely functionality to get `PathPatch` objects and plot polygons. Thanks!
